language: python
dist: "xenial"
sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install coverage
  - pip install coveralls
  - pip install -e .[test]

script:
  - python -m yafowil.tests.__init__
  - coverage run --source src/yafowil -m yafowil.tests.__init__
  - coverage report

after_success:
  - coveralls
